<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.POV5tz8' shared service.

return $this->privates['.service_locator.POV5tz8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\Rest\\CompanyApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\MediaApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\PresentationApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\ProductApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\ProjectApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\ReferanceApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\UserApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\CompanyApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\MediaApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\PresentationApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\ProductApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\ProjectApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\ReferanceApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Rest\\UserApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\Rest\\CompanyApiController::setViewHandler' => '?',
    'App\\Controller\\Rest\\MediaApiController::setViewHandler' => '?',
    'App\\Controller\\Rest\\PresentationApiController::setViewHandler' => '?',
    'App\\Controller\\Rest\\ProductApiController::setViewHandler' => '?',
    'App\\Controller\\Rest\\ProjectApiController::setViewHandler' => '?',
    'App\\Controller\\Rest\\ReferanceApiController::setViewHandler' => '?',
    'App\\Controller\\Rest\\UserApiController::setViewHandler' => '?',
    'App\\Controller\\Rest\\CompanyApiController:setViewHandler' => '?',
    'App\\Controller\\Rest\\MediaApiController:setViewHandler' => '?',
    'App\\Controller\\Rest\\PresentationApiController:setViewHandler' => '?',
    'App\\Controller\\Rest\\ProductApiController:setViewHandler' => '?',
    'App\\Controller\\Rest\\ProjectApiController:setViewHandler' => '?',
    'App\\Controller\\Rest\\ReferanceApiController:setViewHandler' => '?',
    'App\\Controller\\Rest\\UserApiController:setViewHandler' => '?',
]);
