<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Company extends \App\Entity\Company implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'numtel', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'website', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'staffcount', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'sector', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'file', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'activity', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'periodSubscription', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'databasesize', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'slatype', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'supporttype', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'employes', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'equips'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'numtel', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'website', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'staffcount', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'sector', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'file', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'activity', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'periodSubscription', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'databasesize', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'slatype', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'supporttype', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'employes', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'equips'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Company $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumtel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumtel', []);

        return parent::getNumtel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumtel(string $numtel): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumtel', [$numtel]);

        return parent::setNumtel($numtel);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', []);

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite(string $website): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', [$website]);

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getStaffcount(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStaffcount', []);

        return parent::getStaffcount();
    }

    /**
     * {@inheritDoc}
     */
    public function setStaffcount(int $staffcount): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStaffcount', [$staffcount]);

        return parent::setStaffcount($staffcount);
    }

    /**
     * {@inheritDoc}
     */
    public function getSector(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSector', []);

        return parent::getSector();
    }

    /**
     * {@inheritDoc}
     */
    public function setSector(string $sector): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSector', [$sector]);

        return parent::setSector($sector);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(string $file): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivity', []);

        return parent::getActivity();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivity(string $activity): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivity', [$activity]);

        return parent::setActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodSubscription(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodSubscription', []);

        return parent::getPeriodSubscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodSubscription(?\DateTimeInterface $periodSubscription): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodSubscription', [$periodSubscription]);

        return parent::setPeriodSubscription($periodSubscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatabasesize(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatabasesize', []);

        return parent::getDatabasesize();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatabasesize(?int $databasesize): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatabasesize', [$databasesize]);

        return parent::setDatabasesize($databasesize);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlatype(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlatype', []);

        return parent::getSlatype();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlatype(string $slatype): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlatype', [$slatype]);

        return parent::setSlatype($slatype);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupporttype(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupporttype', []);

        return parent::getSupporttype();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupporttype(string $supporttype): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupporttype', [$supporttype]);

        return parent::setSupporttype($supporttype);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(bool $status): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmploye(\App\Entity\Users $employe): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmploye', [$employe]);

        return parent::removeEmploye($employe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquips(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquips', []);

        return parent::getEquips();
    }

    /**
     * {@inheritDoc}
     */
    public function addEquip(\App\Entity\Equip $equip): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEquip', [$equip]);

        return parent::addEquip($equip);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEquip(\App\Entity\Equip $equip): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEquip', [$equip]);

        return parent::removeEquip($equip);
    }

}
