<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMMSHrxP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMMSHrxP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMMSHrxP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMMSHrxP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMMSHrxP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MMSHrxP',
    'container.build_id' => '2125e7d1',
    'container.build_time' => 1586978549,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMMSHrxP');
